### ISSUE TITLE
GMSO Broken issue?

### ISSUE THREAD

**Issue by CalCraven** [mosdef-hub/gmso#540]
I merged in some of the most recent commits to try to finalize PR #492 and realized that I couldn't properly import gmso to check functionality. I cloned a fresh repo with the most recent commit 893534bfe21ea72e05309a00d87008587b6b9fbc, and see the same import error. 

Code to reproduce error:
>```python
> import gmso
>```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/calcraven/Documents/Vanderbilt/Research/git_repos/gmso_check_import_error/gmso/gmso/__init__.py", line 1, in <module>
    from .core.topology import Topology
  File "/Users/calcraven/Documents/Vanderbilt/Research/git_repos/gmso_check_import_error/gmso/gmso/core/topology.py", line 7, in <module>
    from gmso.core.atom import Atom
  File "/Users/calcraven/Documents/Vanderbilt/Research/git_repos/gmso_check_import_error/gmso/gmso/core/atom.py", line 8, in <module>
    from gmso.core.element import Element
  File "/Users/calcraven/Documents/Vanderbilt/Research/git_repos/gmso_check_import_error/gmso/gmso/core/element.py", line 301, in <module>
    elements_dict = {int(key): value for key, value in elements_dict.items()}
  File "/Users/calcraven/Documents/Vanderbilt/Research/git_repos/gmso_check_import_error/gmso/gmso/core/element.py", line 301, in <dictcomp>
    elements_dict = {int(key): value for key, value in elements_dict.items()}
_________________________________
It looks like the most recent changes to gmso that effect element.py come from #536. I might be getting something really wrong, but if there is an issue this is something that should be addressed asap.
________________________________
Version information:
python = 3.7
mbuild = 0.10.13
foyer = 0.7.6
gmso = 0.5.0.dev0

**Comment by CalCraven** [comment]
Seems like the change is in ele.
Version used :
ele = 0.1.0
Version needed:
ele = 0.2.0
